# Generated by Django 5.2.13 on 2026-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
