# Generated by Django 5.2.13 on 2026-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_recurrence_end_event_recurrence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('personal', 'Personnel'), ('meeting', 'Rendez-vous'), ('course', 'Cours')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
