# Generated by Django 5.2.13 on 2026-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_event_event_type_event_recurrence_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_group_id',
        ),
        migrations.AddField(
            model_name='event',
            name='series_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
