# Generated by Django 6.0.4 on 2026-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_created_at_note_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='bg-pink-100', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
