# Generated by Django 6.0.4 on 2026-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_color_note_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
